AWSTemplateFormatVersion: '2010-09-09'
Description: |
  IAM Roles Anywhere infrastructure for Claude Code Playground devcontainer.
  Creates Trust Anchor, IAM Role, and Profile for secure AWS access from
  GitHub Codespaces and local devcontainers.

Parameters:
  RepositoryOwner:
    Type: String
    Default: benoram
    Description: GitHub repository owner for resource tagging

  RepositoryName:
    Type: String
    Default: claude-code-playground
    Description: GitHub repository name for resource tagging

  CACertificateBody:
    Type: String
    Description: |
      PEM-encoded CA certificate to use as Trust Anchor.
      Generate with: openssl req -x509 -newkey rsa:4096 -keyout ca-key.pem -out ca-cert.pem -days 365 -nodes -subj "/CN=devcontainer-claude-code-playground-ca"

  SessionDurationSeconds:
    Type: Number
    Default: 3600
    MinValue: 900
    MaxValue: 43200
    Description: Duration of assumed role sessions (15 min to 12 hours)

Resources:
  #############################################################################
  # Trust Anchor - Registers the CA certificate with IAM Roles Anywhere
  #############################################################################
  TrustAnchor:
    Type: AWS::RolesAnywhere::TrustAnchor
    Properties:
      Name: devcontainer-claude-code-playground-trust-anchor
      Enabled: true
      Source:
        SourceType: CERTIFICATE_BUNDLE
        SourceData:
          X509CertificateData: !Ref CACertificateBody
      Tags:
        - Key: Repository
          Value: !Sub "${RepositoryOwner}/${RepositoryName}"
        - Key: Owner
          Value: !Ref RepositoryOwner
        - Key: Project
          Value: claude-code-playground
        - Key: ManagedBy
          Value: CloudFormation

  #############################################################################
  # IAM Role - The role that will be assumed via Roles Anywhere
  #############################################################################
  DevcontainerRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: devcontainer-claude-code-playground
      Description: IAM role for Claude Code Playground devcontainer access via IAM Roles Anywhere
      MaxSessionDuration: 43200  # 12 hours max
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: rolesanywhere.amazonaws.com
            Action:
              - sts:AssumeRole
              - sts:SetSourceIdentity
              - sts:TagSession
            Condition:
              ArnEquals:
                aws:SourceArn: !GetAtt TrustAnchor.TrustAnchorArn
      # Attach policies as needed for your use case
      # This example provides read-only access - customize as needed
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/ReadOnlyAccess
      Tags:
        - Key: Repository
          Value: !Sub "${RepositoryOwner}/${RepositoryName}"
        - Key: Owner
          Value: !Ref RepositoryOwner
        - Key: Project
          Value: claude-code-playground
        - Key: ManagedBy
          Value: CloudFormation

  #############################################################################
  # Roles Anywhere Profile - Maps certificates to the IAM Role
  #############################################################################
  RolesAnywhereProfile:
    Type: AWS::RolesAnywhere::Profile
    Properties:
      Name: devcontainer-claude-code-playground-profile
      Enabled: true
      DurationSeconds: !Ref SessionDurationSeconds
      RoleArns:
        - !GetAtt DevcontainerRole.Arn
      # Optional: Add session policies to further restrict permissions
      # SessionPolicy: |
      #   {
      #     "Version": "2012-10-17",
      #     "Statement": [
      #       {
      #         "Effect": "Allow",
      #         "Action": "s3:GetObject",
      #         "Resource": "*"
      #       }
      #     ]
      #   }
      Tags:
        - Key: Repository
          Value: !Sub "${RepositoryOwner}/${RepositoryName}"
        - Key: Owner
          Value: !Ref RepositoryOwner
        - Key: Project
          Value: claude-code-playground
        - Key: ManagedBy
          Value: CloudFormation

Outputs:
  TrustAnchorArn:
    Description: ARN of the Trust Anchor (needed for credential helper)
    Value: !GetAtt TrustAnchor.TrustAnchorArn
    Export:
      Name: !Sub "${AWS::StackName}-TrustAnchorArn"

  ProfileArn:
    Description: ARN of the Roles Anywhere Profile (needed for credential helper)
    Value: !GetAtt RolesAnywhereProfile.ProfileArn
    Export:
      Name: !Sub "${AWS::StackName}-ProfileArn"

  RoleArn:
    Description: ARN of the IAM Role (needed for credential helper)
    Value: !GetAtt DevcontainerRole.Arn
    Export:
      Name: !Sub "${AWS::StackName}-RoleArn"

  RoleName:
    Description: Name of the IAM Role
    Value: !Ref DevcontainerRole
    Export:
      Name: !Sub "${AWS::StackName}-RoleName"

  SetupInstructions:
    Description: Next steps after deployment
    Value: |
      1. Generate end-entity certificate signed by your CA
      2. Base64 encode certificate and private key
      3. Add as GitHub Codespaces secrets:
         - ROLES_ANYWHERE_CERTIFICATE
         - ROLES_ANYWHERE_PRIVATE_KEY
         - ROLES_ANYWHERE_TRUST_ANCHOR_ARN
         - ROLES_ANYWHERE_PROFILE_ARN
         - ROLES_ANYWHERE_ROLE_ARN
